# Generated by Django 4.2.7 on 2023-12-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("height", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winter",
                    models.CharField(
                        choices=[
                            ("1A", "1A"),
                            ("1B", "1B"),
                            ("2A", "2A"),
                            ("2B", "2B"),
                            ("3A", "3A"),
                            ("3B", "3B"),
                        ],
                        default="1A",
                        max_length=2,
                    ),
                ),
                (
                    "summer",
                    models.CharField(
                        choices=[
                            ("1A", "1A"),
                            ("1B", "1B"),
                            ("2A", "2A"),
                            ("2B", "2B"),
                            ("3A", "3A"),
                            ("3B", "3B"),
                        ],
                        default="1A",
                        max_length=2,
                    ),
                ),
                (
                    "autumn",
                    models.CharField(
                        choices=[
                            ("1A", "1A"),
                            ("1B", "1B"),
                            ("2A", "2A"),
                            ("2B", "2B"),
                            ("3A", "3A"),
                            ("3B", "3B"),
                        ],
                        default="1A",
                        max_length=2,
                    ),
                ),
                (
                    "spring",
                    models.CharField(
                        choices=[
                            ("1A", "1A"),
                            ("1B", "1B"),
                            ("2A", "2A"),
                            ("2B", "2B"),
                            ("3A", "3A"),
                            ("3B", "3B"),
                        ],
                        default="1A",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PerevalAdd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beauty_title", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("other_titles", models.CharField(max_length=255)),
                ("connect", models.CharField(max_length=255)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "coords_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perevalapp.coord",
                    ),
                ),
                (
                    "level_diff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perevalapp.level",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perevalapp.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                (
                    "pereval_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perevalapp.perevaladd",
                    ),
                ),
            ],
        ),
    ]
