# Generated by Django 4.2.7 on 2023-12-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perevalapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perevaladd",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("pending", "is being done"),
                    ("accepted", "successfully moderated"),
                    ("rejected", "was moderated but was not accepted"),
                ],
                default="new",
                max_length=10,
            ),
        ),
    ]
