# Generated by Django 4.2.7 on 2023-12-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perevalapp", "0007_alter_images_pereval_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
